name: 宠汪汪积分兑换奖品

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 0-16/8 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run jd_joy_reward
              run: npm install
            - run: node jd_joy_reward.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
